# Generated by Django 5.1.4 on 2024-12-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseCode', models.CharField(max_length=150)),
                ('Credits', models.IntegerField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('FacultyID', models.AutoField(primary_key=True, serialize=False)),
                ('FacultyName', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('GradeLetter', models.CharField(max_length=1)),
                ('GradeNumeric', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=150)),
                ('LName', models.CharField(max_length=150)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=100)),
                ('DateOfBirthDay', models.DateField()),
                ('FacultyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingToCourse',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('RecordingDate', models.DateField()),
                ('Semester', models.CharField(max_length=150)),
                ('AcademicYear', models.CharField(max_length=100)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionapp.courses')),
                ('GradeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionapp.grades')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionapp.students')),
            ],
        ),
    ]
